# =====================================================================
# job.properties
# Apache Oozie job configuration — Stray Kids Spotify Streaming Analytics
# Run as: oozie job -oozie http://<oozie-host>:11000/oozie -config job.properties -run
# =====================================================================

nameNode=hdfs://sandbox-hdp.hortonworks.com:8020
jobTracker=sandbox-hdp.hortonworks.com:8050
queueName=default

oozie.use.system.libpath=true
oozie.wf.application.path=${nameNode}/user/maria_dev/spotify/workflow
